// Pure renderer for `aitcc app init`. Lives separately from the handler
// so its only dependency is on the answers object; tests pin the literal
// output without spinning up any I/O. The yaml is hand-rolled (rather
// than going through `yaml.stringify` + comment injection) because the
// commented-out optional block needs precise placement to be useful, and
// mixing programmatic comments into a `Document` ends up more brittle
// than a template string.

export interface InitAnswers {
  readonly workspaceId: number;
  readonly titleKo: string;
  readonly titleEn: string;
  readonly appName: string;
  readonly csEmail: string;
  readonly subtitle: string;
  readonly description: string;
  readonly categoryIds: readonly number[];
}

export function renderInitYaml(answers: InitAnswers): string {
  const description = indentBlock(answers.description, '  ');
  return `# Project context — read by every aitcc command in this directory tree.
# Generated by \`aitcc app init\` (https://github.com/apps-in-toss-community/console-cli).
workspaceId: ${answers.workspaceId}
# miniAppId is written back automatically by \`aitcc app register\`.

# --- App manifest (required) ---
titleKo: ${yamlDoubleQuoted(answers.titleKo)}
titleEn: ${yamlDoubleQuoted(answers.titleEn)}
appName: ${answers.appName}
csEmail: ${answers.csEmail}
subtitle: ${yamlDoubleQuoted(answers.subtitle)}
description: |-
${description}
categoryIds: [${answers.categoryIds.join(', ')}]
logo: ./assets/logo.png
horizontalThumbnail: ./assets/thumbnail.png
verticalScreenshots:
  - ./assets/screenshot-1.png
  - ./assets/screenshot-2.png
  - ./assets/screenshot-3.png

# --- Optional fields (uncomment + fill in if needed) ---
# homePageUri: "https://example.com/"
# logoDarkMode: ./assets/logo-dark.png
# keywords: [foo, bar]
# horizontalScreenshots:
#   - ./assets/horizontal-1.png
`;
}

// Forces a quoted scalar so colons, leading whitespace, or yaml-significant
// chars in user input can't accidentally break the document shape.
function yamlDoubleQuoted(value: string): string {
  const escaped = value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  return `"${escaped}"`;
}

// `|-` block scalars require every content line to share the same indent;
// without this helper a multi-line description would silently corrupt the
// surrounding document.
function indentBlock(value: string, prefix: string): string {
  return value
    .split('\n')
    .map((line) => `${prefix}${line}`)
    .join('\n');
}
