import { defineCommand } from 'citty';
import { ExitCode } from '../exit.js';
import { exitAfterFlush } from '../flush.js';
import { emitJson } from './_shared.js';

// Shell completion scripts for aitcc.
//
// Philosophy: keep it static + shallow. citty does not ship its own
// completion generator, and introspecting a live command tree at runtime
// would duplicate the source of truth. Instead we hard-code the one-level
// subcommand list that matters for tab-completion; the shell scripts only
// need to know top-level commands and the common flags. Deeper sub-sub
// completion (e.g. `app bundles ls`) stays uncompleted — users type
// `bundles <TAB>` and the shell falls back to filenames, which is fine.
//
// Install flow is one-shot per shell:
//   bash  →  aitcc completion bash > /etc/bash_completion.d/aitcc
//             or `source <(aitcc completion bash)` in .bashrc
//   zsh   →  aitcc completion zsh > "${fpath[1]}/_aitcc" && autoload -U _aitcc
//             (or drop it in ~/.zsh/completions/_aitcc and rebuild fpath)
//   fish  →  aitcc completion fish > ~/.config/fish/completions/aitcc.fish
//
// install.sh prints the right one-liner after install based on $SHELL;
// we don't modify user rc files automatically.

// Top-level commands.
const TOP_LEVEL: readonly string[] = [
  'whoami',
  'login',
  'logout',
  'upgrade',
  'workspace',
  'app',
  'members',
  'keys',
  'notices',
  'me',
  'completion',
];

// Subcommands per namespace. Order is for display (alpha).
const SUB_COMMANDS: Record<string, readonly string[]> = {
  workspace: ['ls', 'partner', 'segments', 'show', 'terms', 'use'],
  app: [
    'bundles',
    'categories',
    'certs',
    'events',
    'ls',
    'messages',
    'metrics',
    'ratings',
    'register',
    'reports',
    'service-status',
    'share-rewards',
    'show',
    'status',
    'templates',
  ],
  notices: ['categories', 'ls', 'show'],
  me: ['terms'],
  completion: ['bash', 'zsh', 'fish'],
};

function emitBash(): string {
  const top = TOP_LEVEL.join(' ');
  // Per-namespace case branch. We keep this small — only the immediate
  // subcommand layer is offered; the shell then falls back to filename
  // completion for the 3rd word onward.
  const cases: string[] = [];
  for (const [ns, subs] of Object.entries(SUB_COMMANDS)) {
    cases.push(`    ${ns})`);
    cases.push(`      COMPREPLY=( $(compgen -W "${subs.join(' ')}" -- "$cur") )`);
    cases.push('      return 0 ;;');
  }
  return `# bash completion for aitcc. Generated by \`aitcc completion bash\`.
# Install:
#   aitcc completion bash > /etc/bash_completion.d/aitcc
#   # or add to ~/.bashrc:
#   source <(aitcc completion bash)

_aitcc_completion() {
  local cur prev
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"

  if [[ $COMP_CWORD -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "${top}" -- "$cur") )
    return 0
  fi

  case "\${COMP_WORDS[1]}" in
${cases.join('\n')}
  esac

  return 0
}

complete -F _aitcc_completion aitcc
`;
}

function emitZsh(): string {
  // Use zsh's _arguments with a nested state machine. Keep the definition
  // readable; zsh users often inspect their completion files.
  const top = TOP_LEVEL.join(' ');
  const nsClauses: string[] = [];
  for (const [ns, subs] of Object.entries(SUB_COMMANDS)) {
    nsClauses.push(`      ${ns}) _values 'subcommand' ${subs.map((s) => `'${s}'`).join(' ')} ;;`);
  }
  return `#compdef aitcc
# zsh completion for aitcc. Generated by \`aitcc completion zsh\`.
# Install:
#   aitcc completion zsh > "\${fpath[1]}/_aitcc"
#   # then in a fresh shell (or run \`autoload -U compinit && compinit\`)

_aitcc() {
  local -a commands
  commands=(${TOP_LEVEL.map((c) => `'${c}'`).join(' ')})

  if (( CURRENT == 2 )); then
    _values 'command' ${TOP_LEVEL.map((c) => `'${c}'`).join(' ')}
    return
  fi

  case "\${words[2]}" in
${nsClauses.join('\n')}
  esac
}

_aitcc "$@"
# ${top}
`;
}

function emitFish(): string {
  const lines: string[] = [
    '# fish completion for aitcc. Generated by `aitcc completion fish`.',
    '# Install:',
    '#   aitcc completion fish > ~/.config/fish/completions/aitcc.fish',
    '',
  ];
  // Top-level commands (only when no subcommand given yet).
  for (const c of TOP_LEVEL) {
    lines.push(`complete -c aitcc -n "__fish_use_subcommand" -a "${c}" -f`);
  }
  for (const [ns, subs] of Object.entries(SUB_COMMANDS)) {
    for (const s of subs) {
      lines.push(`complete -c aitcc -n "__fish_seen_subcommand_from ${ns}" -a "${s}" -f`);
    }
  }
  return `${lines.join('\n')}\n`;
}

export const completionCommand = defineCommand({
  meta: {
    name: 'completion',
    description: 'Emit a shell completion script for bash, zsh, or fish.',
  },
  args: {
    shell: {
      type: 'positional',
      description: 'Target shell: bash, zsh, or fish.',
      required: false,
    },
    json: {
      type: 'boolean',
      description: "Emit { ok: false, reason: 'invalid-shell' } on bad input.",
      default: false,
    },
  },
  async run({ args }) {
    const raw = args.shell === undefined ? '' : String(args.shell).toLowerCase();
    if (raw === 'bash') {
      process.stdout.write(emitBash());
      return exitAfterFlush(ExitCode.Ok);
    }
    if (raw === 'zsh') {
      process.stdout.write(emitZsh());
      return exitAfterFlush(ExitCode.Ok);
    }
    if (raw === 'fish') {
      process.stdout.write(emitFish());
      return exitAfterFlush(ExitCode.Ok);
    }
    // No shell given (or unknown) — print usage to stderr. We expose a
    // --json failure mode so agent-plugin can probe capability without
    // parsing human text.
    if (args.json) {
      emitJson({
        ok: false,
        reason: 'invalid-shell',
        allowed: ['bash', 'zsh', 'fish'],
        message: `completion shell must be one of: bash, zsh, fish (got ${JSON.stringify(raw)})`,
      });
    } else {
      process.stderr.write(
        'Usage: aitcc completion <bash|zsh|fish>\n' +
          '\n' +
          'Examples:\n' +
          '  aitcc completion bash > /etc/bash_completion.d/aitcc\n' +
          // biome-ignore lint/suspicious/noTemplateCurlyInString: literal zsh syntax, not a JS template placeholder
          '  aitcc completion zsh  > "${fpath[1]}/_aitcc"\n' +
          '  aitcc completion fish > ~/.config/fish/completions/aitcc.fish\n',
      );
    }
    return exitAfterFlush(ExitCode.Usage);
  },
});
